#!/bin/bash
#SBATCH --job-name=dft-2190
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=2
#SBATCH --gpus=a100l:1
#SBATCH --time=3-00:00:00
#SBATCH --mem=32Gb
#SBATCH --exclude=cn-k[001-002]

module load anaconda/3
module load cuda/12.2.2
conda activate crysrl

# module load cuda/12.2.2
module use --priority 100 /home/mila/p/prashant.govindarajan/pkgs/nvhpc_2023_237_Linux_x86_64_cuda_multi/modulefiles
module load nvhpc-hpcx-cuda12
export NVHPC_CUDA_HOME="$CUDA_HOME"
export OMP_NUM_THREADS=2

## PPO
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-630 exp.seed=10 env.seed=10 env.index=630
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-630 exp.seed=20 env.seed=20 env.index=630
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-630 exp.seed=30 env.seed=30 env.index=630

# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-2190 exp.seed=10 env.seed=10 env.index=2190 wandb.wandb_group=PPO-DEFAULT-2190
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-2190 exp.seed=20 env.seed=20 env.index=2190 wandb.wandb_group=PPO-DEFAULT-2190
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-2190 exp.seed=30 env.seed=30 env.index=2190 wandb.wandb_group=PPO-DEFAULT-2190


# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-3403 exp.seed=10 env.seed=10 env.index=3403 wandb.wandb_group=PPO-DEFAULT-3403
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-3403 exp.seed=20 env.seed=20 env.index=3403 wandb.wandb_group=PPO-DEFAULT-3403
# python ppo.py wandb.mode=online exp.exp_name=ppo-basic-3403 exp.seed=30 env.seed=30 env.index=3403 wandb.wandb_group=PPO-DEFAULT-3403

## SAC
# python sac.py wandb.mode=online exp.exp_name=sac-basic-630 exp.seed=10 env.seed=10 env.index=630 wandb.wandb_group=SAC-DEFAULT-630
# python sac.py wandb.mode=online exp.exp_name=sac-basic-630 exp.seed=20 env.seed=20 env.index=630 wandb.wandb_group=SAC-DEFAULT-630
# python sac.py wandb.mode=online exp.exp_name=sac-basic-630 exp.seed=30 env.seed=30 env.index=630 wandb.wandb_group=SAC-DEFAULT-630

# python sac.py wandb.mode=online exp.exp_name=sac-basic-2190 exp.seed=10 env.seed=10 env.index=2190 wandb.wandb_group=SAC-DEFAULT-2190
# python sac.py wandb.mode=online exp.exp_name=sac-basic-2190 exp.seed=20 env.seed=20 env.index=2190 wandb.wandb_group=SAC-DEFAULT-2190
# python sac.py wandb.mode=online exp.exp_name=sac-basic-2190 exp.seed=30 env.seed=30 env.index=2190 wandb.wandb_group=SAC-DEFAULT-2190

# python sac.py wandb.mode=online exp.exp_name=sac-basic-3403 exp.seed=10 env.seed=10 env.index=3403 wandb.wandb_group=SAC-DEFAULT-3403
# python sac.py wandb.mode=online exp.exp_name=sac-basic-3403 exp.seed=20 env.seed=20 env.index=3403 wandb.wandb_group=SAC-DEFAULT-3403
python sac.py wandb.mode=online exp.exp_name=sac-basic-3403 exp.seed=30 env.seed=30 env.index=3403 wandb.wandb_group=SAC-DEFAULT-3403


